import pandas as pd

os_family = ['Symbian OS',	'Other',	'BlackBerry OS',	'Android',	'Chrome OS',	'Mac OS X',	'Linux',	'Firefox OS',	'null_operating_system',	'FreeBSD',	'KaiOS',	'Fedora',	'Windows NT 4.0',	'Windows',	'Windows Phone',	'iOS',	'Ubuntu',	'Tizen',	'Solaris',	'NetBSD']

country_codes = ['UA',	'DZ',	'JP',	'BH',	'HR',	'HU',	'IQ',	'LI',	'BQ',	'MW',	'KM',	'TM',	'KI',	'AQ',	'WF',	'BL',	'NF',	'ROW',	'TZ',	'ET',	'CW',	'TK',	'GB',	'PL',	'KW',	'TR',	'DK',	'SG',	'TH',	'PS',	'CR',	'BG',	'AD',	'BS',	'XK',	'SB',	'FO',	'FI',	'PG',	'SL',	'AE',	'GR',	'NG',	'KR',	'DO',	'RO',	'SV',	'CZ',	'LY',	'OM',	'HN',	'LR',	'PF',	'MK',	'FJ',	'AS',	'FK',	'TV',	'KP',	'PK',	'ZA',	'PY',	'CM',	'BA',	'AL',	'MO',	'ML',	'GE',	'EE',	'CO',	'JO',	'MX',	'GY',	'KG',	'BZ',	'LB',	'NE',	'UG',	'SC',	'GD',	'SY',	'TO',	'ER',	'SH',	'QA',	'SA',	'XX',	'NL',	'VN',	'VE',	'UZ',	'null_country_code',	'AI',	'CD',	'VU',	'YT',	'EH',	'EN',	'MN',	'NI',	'BV',	'ID',	'BR',	'PT',	'NZ',	'IL',	'CL',	'MT',	'BY',	'TW',	'MR',	'PW',	'BI',	'DJ',	'VI',	'SR',	'CF',	'MS',	'ZW',	'SD',	'AX',	'ES',	'PE',	'IE',	'SE',	'BF',	'KY',	'VC',	'MU',	'ZM',	'SS',	'PM',	'SZ',	'NR',	'US',	'DE',	'PH',	'AT',	'KH',	'SO',	'LT',	'NP',	'BB',	'unknown',	'MF',	'SJ',	'CX',	'RS',	'JE',	'IT',	'CY',	'BN',	'AU',	'KE',	'MY',	'AR',	'LV',	'SI',	'GP',	'CU',	'GI',	'LS',	'TL',	'GS',	'MM',	'RE',	'IM',	'MA',	'CH',	'BW',	'HT',	'TJ',	'LA',	'GF',	'CG',	'YE',	'TG',	'MP',	'AW',	'BT',	'CC',	'CI',	'KN',	'BE',	'PR',	'NO',	'LK',	'GH',	'NC',	'SX',	'LC',	'GQ',	'FM',	'HK',	'EC',	'IN',	'MD',	'TT',	'IR',	'TN',	'SN',	'TD',	'MZ',	'AG',	'GN',	'ST',	'VA',	'GT',	'VG',	'RU',	'EG',	'PA',	'LU',	'AO',	'BJ',	'BO',	'JM',	'TC',	'CV',	'MH',	'MG',	'DM',	'AM',	'CA',	'CN',	'AZ',	'SK',	'BM',	'AF',	'UY',	'BD',	'MC',	'IS',	'ZZ',	'NA',	'RW',	'GL',	'WS',	'IO',	'GA',	'TF',	'FR',	'KZ',	'ME',	'T1',	'GU',	'CK',	'MQ',	'SM',	'MV',	'GG',	'GM',	'GW',	'NU',	'PN',	'UM']

platforms = ['twitter.com',	'monster',	'quora.com',	'laborum cl',	'partnerships',	'pulsa',	'babylon',	'duckduckgo',	'seriousteachers',	'vk.com',	'indeed',	'reddit.com',	'upward',	'youtube',	'careerjet',	'almehn',	'karriereguiden',	'system',	'blog.naver.com',	'careerbuilder',	'auone',	'overseas',	'education_canada',	'livejournal.com',	'snap',	'jobs.cz',	'centrum.cz',	'career.co.kr',	'avg',	'baidu',	'appcast',	'msn',	'taboola',	'xing',	'manda-te',	'affiliate',	'instagram.com',	'instagram',	'jobrapido',	'aol',	'tut.by',	'eslcafe',	'trovolavoro',	'tas',	'preply',	'tiktok',	'quizlet',	'bebee',	'glassdoor',	'reddit',	'occmundial',	'organic',	'outbrain',	'bayt',	'jobsinjapan',	'stellenwerk-bochum',	'stellenanzeigen',	'disqus.com',	'kvasir',	'RWTH aachen',	'career_co_kr',	'youtube.com',	'teachaway',	'studentjob',	'uraopas.fi',	'stellananzeigen',	'netjobs',	'facebook.com',	'intercom',	'ecosia.org',	'unknown',	'leitschiff',	'internation',	'jobcase',	'plus.google.com',	'bridge.edu',	'referral',	'oetjobs.com',	'mail.naver.com',	'manabitai.tumblr.com',	'(direct)',	'yandex',	'tefl',	'quora',	'buzzfeed.com',	'demio',	'karriereguiden.dk',	'netjobs.com',	'jobportal-augsburg',	'mojeek',	'360.cn',	'bing',	'braze',	'jooble',	'supply',	'getpocket.com',	'so.com',	'linktree',	'qwant.com',	'interpals.net',	'biglobe',	'seznam',	'virgilio',	'bumeran',	'event',	'goo.ne',	'gaijinpot',	'',	'facebook',	'infojobs',	'ask',	'sogou',	'go.mail.ru',	'daum',	'ukr',	'rambler',	'jobteaser',	'lycos',	'university of kassel',	'tefl.com',	'internationalteflacademy.com',	'pinterest.com',	'linkedin',	'asa',	'stepstone',	'jobsuma',	'yammer.com',	'teflnet',	'jobportal augsburg',	'toplanguagejobs',	'vimeo.com',	'ruhr universitat',	'op-empleo',	'cadremploi',	'uraopas',	'talent',	'rakuten',	'onet',	'startsiden',	'karriereguiden.no',	'peachjar',	'almehan',	'google',	'other',	'yahoo',	'naver',	'webinar',	'remote.co',	'search.smt.docomo',	'atresmedia',	'pracuj',	'nvb',	'goldenline.pl']

index = pd.MultiIndex.from_product([os_family, country_codes, platforms], names=['os_family', 'country_code', 'platform'])

df = pd.DataFrame(index=index).reset_index()

df['weight'] = 1

df.to_csv("incrementality_weights.csv")
